[build]
  command = "npm cache clean --force && rm -f package-lock.json && npm install && npm run build:clean"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "8.19.0"
  # Clear cache on problematic builds
  NPM_CONFIG_CACHE = "/opt/build/cache/npm"
  # Disable problematic binary downloads during build
  MSGPACKR_PREBUILDS = "false"
  # Handle legacy peer dependencies
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[functions]
  node_bundler = "esbuild"

# Cache optimization
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 