[build]
  command = "npm cache clean --force && npm install --legacy-peer-deps && npm rebuild lmdb && npm run build:clean"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "8.19.0"
  # Clear cache on problematic builds
  NPM_CONFIG_CACHE = "/opt/build/cache/npm"
  # Disable problematic binary downloads during build
  MSGPACKR_PREBUILDS = "false"
  # Force rebuild of native modules
  npm_config_build_from_source = "true"
  npm_config_cache = "/opt/build/cache/npm"

[functions]
  node_bundler = "esbuild"

# Cache optimization
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 